server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
   
spring:
  

  datasource:
    druid:
      url: jdbc:mysql://101.132.77.169:3306/361im?characterEncoding=utf-8&serverTimezone=UTC
      username: 361im
      password: Itboye2015
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
      
      
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 3600



  clientchatkey: LiveChatClientKeyboyejim
     
